apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-app-config
data:
  appsettings.json: |
    {
      "MongoDbSettings": {
            "ConnectionString": "mongodb://admin:admin@localhost:8000/?authSource=admin",
            "Database": "movie_booking_db"
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-booking-system-config
data:
  database_url: mongodb-service
  user_service_url: user-service
  database_user_db: user_db
  database_name: movie_booking_db