apiVersion: v1
kind: ConfigMap
metadata:
  name: paymentservice-appconfig
data:
  appsettings.json: |
    {
      "MongoDbSettings": {
            "ConnectionString": "mongodb://admin:admin@localhost:8000/?authSource=admin",
            "Database": "movie_booking_db"
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-booking-system-config
data:
  database_url: localhost:8000
  user_service_url: 127.0.0.1:4000
  database_user_db: NIL
  database_name: movie_booking_db
