apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
      - name: payment-app
        image: anilkdora/payment-app:latest
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        env:
        - name: MONGODB_ADMIN_USER_NAME
          valueFrom:
            secretKeyRef:
              name: movie-booking-system-secret
              key: mongodb-root-username
        - name: MONGODB_ADMIN_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: movie-booking-system-secret
              key: mongodb-root-password
        - name: PORT
          value: "4000"
        - name: MONGODB_URL_PATH
          valueFrom:
            configMapKeyRef:
              name: movie-booking-system-config
              key: database_url
        - name: MONGODB_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: movie-booking-system-config
              key: database_name
              key: database_name
        - name: MONGODB_USER_DB
          valueFrom:
            configMapKeyRef:
              name: movie-booking-system-config
              key: database_user_db
        - name: MONGODB_URL
          value: "mongodb://$(MONGODB_ADMIN_USER_NAME):$(MONGODB_ADMIN_USER_PASSWORD)@$(MONGODB_URL_PATH)/?authSource=admin"
        - name: DB_CONNECTION_RETRY_TIMEOUT  
          value: "5000"          
        - name: AUTH_ROOT_URL
          valueFrom:
            configMapKeyRef:
              name: movie-booking-system-config
              key: user_service_url
        - name: AUTH_URL
          value: "$(AUTH_ROOT_URL)"
      volumes:
        - name: config-volume
          configMap:
            name: paymentservice-appconfig
